services:
  - type: web
    runtime: node
    name: get-togetherer-api
    repo: https://github.com/kosta-stratigos/get-togetherer
    branch: main
    plan: starter
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    disk:
      name: poll-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
